---
title: "About Tab"
author: "Lucero Mejia"
date: "March 9, 2019"
output: html_document
---

As time has evolved, more musical instruments have developed resulting in more sophisticated and complex sounds being produced. The rhythm, pitch, timbre, and lyrics of songs have all changed along with the changes in cultures over time. To help analyze these changes we will use Spotify's and Billboard's Top 100 data. Spotify is a digital music service that gives you access to millions of songs, podcasts and videos from artists all over the world.[^1] Consequently, Billboard Top 100 is the music industry's standard record chart in the United States fro songs. Chart rankings are based on sales (physical and digital), radio play, and online streaming in the United States. A new chart is compiled and officially released to the public every Tuesday.[^2] As a result, we can determine why songs become popular by analyzing their rhythm (placement of sounds in time), pitch (the quality that makes it possible to judge sounds as "higher" or "lower") and timbre (the quality of music note or sound that distinguishes different types of musical instruments, or voices) for specific years since 1950.

Users can interactively choose a year they are interested in to get a closer look at details to help answer questions such as:

- How do the **average number of words** of all songs in 2000 compare to the year 2010?

- How does the **average number of words per minute** for the years 1980, 1990, 2000, 2010, and 2015 compare? Does it increase or decrease?

- How do the top 5 popular songs from the years 1965, 1975, 1985, 1995, and 2005 compare from each other?

- How do danceability, energy, loudness, tempo, and valence change from 1980 to 1990?


##References

[^1]: https://www.pocket-lint.com/apps/news/spotify/139236-what-is-spotify-and-how-does-it-work

[^2]: https://en.wikipedia.org/wiki/Billboard_Hot_100
