---
title: "Spotify & Billboards top 100"
author: "Team AD1: Lucero Mejia, Jason Yan, Shea Frantz, Schawnery Lin"
date: "February 22, 2019"
output: html_document
---

## Problem Domain: Spotify and Billboard Top 100

Spotify is a digital music service that gives you access to millions of songs, podcasts and videos from artists all over the world. A user can sign up for Spotify Premium for a monthly subscription fee. With _Spotify Premium_ a user is granted access to features such as ad-free streaming, unlimited skips and extreme quality streaming versus with _Spotify Free_ a user can play music on shuffle mode and skip up to six times per hour, every hour and Spotify Radio is not available.[^1]

Billboard Top 100 is the music industry standard record chart in the United States for songs. Chart rankings are based on sales (physical and digital), radio play, and online streaming in the United States. A new chart is compiled and officially released to the public every Tuesday.[^2]

As todays modern world continues to strive for efficency and quickeness, Spotify and Billboard Top 100 help with reaching these two goals. Streaming allows you to listen to music without having to download files (e.g. MP3, WMA, AAC) from the internet. In other words, with streaming, an individual can start listening to music almost immediately![^3] As a result, we can determine why songs become popular and accumulate a large number of streams by analyzing their rhythm (placement of sounds in time), pitch (the quality that makes it possible to judge sounds as "higher" or "lower") and timbre (the quality of music note or sound that distinguishes different types of musical instruments, or voices). 



#### _Question 1_
Which genre has the highest number of streams?

This quesiton is of interest because we can analyze which genre is popular among all the different number of genres that are in todays music industry. Our data sets will support this by using Billboards data for the top 50 songs for a particular years and then plug those songs into spotify to tell us the number of streams. 

#### _Question 2_
Highest stream count of the top song within each genre? In other words, from each genre, what is their highest streamed song? 

This quesiton is of interest because we can compare top songs within genres, and compare that to popular genres. From this, we can assess how much influence the top songs within a genre has over the popularity of the entire genre. Our data sets will support this as we will utilize the popular songs with their genre tags associated with them. 

#### _Question 3_
How do the number of streams compare from 1950 to 2015?

This question is of interest because we can analyze the trends of users within the time frame of (x year to y year). From the data we collect, we can assess the number of users, and analyze if streaming as a platform has increased.

#### _Question 4_
How do the rythm, pitch, and timbre compare across several different genres?

This question is of interest to analyze themes and motifs among different genres, and how similarities of songs rhythm, pitch, and timbre may affect popularity within genre. Our data sets will support this by providing values of pitch and timbre from Spotify's audio analysis for a particular song, chosen from Billboards top 100. 

## Reference
[^1]: https://www.pocket-lint.com/apps/news/spotify/139236-what-is-spotify-and-how-does-it-work

[^2]: https://en.wikipedia.org/wiki/Billboard_Hot_100

[^3]: https://www.lifewire.com/what-is-streaming-music-2438445
